// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package kernel

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadFunction returns the embedded CollectionSpec for function.
func loadFunction() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FunctionBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load function: %w", err)
	}

	return spec, err
}

// loadFunctionObjects loads function and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*functionObjects
//	*functionPrograms
//	*functionMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFunctionObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFunction()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// functionSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type functionSpecs struct {
	functionProgramSpecs
	functionMapSpecs
	functionVariableSpecs
}

// functionProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type functionProgramSpecs struct {
	UprobeEntry *ebpf.ProgramSpec `ebpf:"uprobe_entry"`
	UprobeExit  *ebpf.ProgramSpec `ebpf:"uprobe_exit"`
}

// functionMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type functionMapSpecs struct {
	FunctionEvents *ebpf.MapSpec `ebpf:"function_events"`
	StartTimes     *ebpf.MapSpec `ebpf:"start_times"`
}

// functionVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type functionVariableSpecs struct {
}

// functionObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFunctionObjects or ebpf.CollectionSpec.LoadAndAssign.
type functionObjects struct {
	functionPrograms
	functionMaps
	functionVariables
}

func (o *functionObjects) Close() error {
	return _FunctionClose(
		&o.functionPrograms,
		&o.functionMaps,
	)
}

// functionMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFunctionObjects or ebpf.CollectionSpec.LoadAndAssign.
type functionMaps struct {
	FunctionEvents *ebpf.Map `ebpf:"function_events"`
	StartTimes     *ebpf.Map `ebpf:"start_times"`
}

func (m *functionMaps) Close() error {
	return _FunctionClose(
		m.FunctionEvents,
		m.StartTimes,
	)
}

// functionVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFunctionObjects or ebpf.CollectionSpec.LoadAndAssign.
type functionVariables struct {
}

// functionPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFunctionObjects or ebpf.CollectionSpec.LoadAndAssign.
type functionPrograms struct {
	UprobeEntry *ebpf.Program `ebpf:"uprobe_entry"`
	UprobeExit  *ebpf.Program `ebpf:"uprobe_exit"`
}

func (p *functionPrograms) Close() error {
	return _FunctionClose(
		p.UprobeEntry,
		p.UprobeExit,
	)
}

func _FunctionClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed function_bpfel.o
var _FunctionBytes []byte
