// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package kernel

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type hardwarePerfStats struct {
	_                  structs.HostLayout
	Cycles             uint64
	Instructions       uint64
	RefCycles          uint64
	CacheReferences    uint64
	CacheMisses        uint64
	Branches           uint64
	BranchMisses       uint64
	L1dLoads           uint64
	L1dLoadMisses      uint64
	L1dStores          uint64
	L1dStoreMisses     uint64
	L1dPrefetches      uint64
	L1dPrefetchMisses  uint64
	L1iLoads           uint64
	L1iLoadMisses      uint64
	L1iPrefetches      uint64
	LlcLoads           uint64
	LlcLoadMisses      uint64
	LlcStores          uint64
	LlcStoreMisses     uint64
	LlcPrefetches      uint64
	LlcPrefetchMisses  uint64
	DtlbLoads          uint64
	DtlbLoadMisses     uint64
	DtlbStores         uint64
	DtlbStoreMisses    uint64
	DtlbPrefetches     uint64
	DtlbPrefetchMisses uint64
	TlbLoads           uint64
	TlbLoadMisses      uint64
	BpuLoads           uint64
	BpuLoadMisses      uint64
}

// loadHardware returns the embedded CollectionSpec for hardware.
func loadHardware() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HardwareBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hardware: %w", err)
	}

	return spec, err
}

// loadHardwareObjects loads hardware and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hardwareObjects
//	*hardwarePrograms
//	*hardwareMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHardwareObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHardware()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hardwareSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hardwareSpecs struct {
	hardwareProgramSpecs
	hardwareMapSpecs
	hardwareVariableSpecs
}

// hardwareProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hardwareProgramSpecs struct {
	OnBpuLoadMisses      *ebpf.ProgramSpec `ebpf:"on_bpu_load_misses"`
	OnBpuLoads           *ebpf.ProgramSpec `ebpf:"on_bpu_loads"`
	OnBranchMisses       *ebpf.ProgramSpec `ebpf:"on_branch_misses"`
	OnBranches           *ebpf.ProgramSpec `ebpf:"on_branches"`
	OnCacheMisses        *ebpf.ProgramSpec `ebpf:"on_cache_misses"`
	OnCacheReferences    *ebpf.ProgramSpec `ebpf:"on_cache_references"`
	OnCpuCycles          *ebpf.ProgramSpec `ebpf:"on_cpu_cycles"`
	OnDtlbLoadMisses     *ebpf.ProgramSpec `ebpf:"on_dtlb_load_misses"`
	OnDtlbLoads          *ebpf.ProgramSpec `ebpf:"on_dtlb_loads"`
	OnDtlbPrefetchMisses *ebpf.ProgramSpec `ebpf:"on_dtlb_prefetch_misses"`
	OnDtlbPrefetches     *ebpf.ProgramSpec `ebpf:"on_dtlb_prefetches"`
	OnDtlbStoreMisses    *ebpf.ProgramSpec `ebpf:"on_dtlb_store_misses"`
	OnDtlbStores         *ebpf.ProgramSpec `ebpf:"on_dtlb_stores"`
	OnInstructions       *ebpf.ProgramSpec `ebpf:"on_instructions"`
	OnL1dLoadMisses      *ebpf.ProgramSpec `ebpf:"on_l1d_load_misses"`
	OnL1dLoads           *ebpf.ProgramSpec `ebpf:"on_l1d_loads"`
	OnL1dPrefetchMisses  *ebpf.ProgramSpec `ebpf:"on_l1d_prefetch_misses"`
	OnL1dPrefetches      *ebpf.ProgramSpec `ebpf:"on_l1d_prefetches"`
	OnL1dStoreMisses     *ebpf.ProgramSpec `ebpf:"on_l1d_store_misses"`
	OnL1dStores          *ebpf.ProgramSpec `ebpf:"on_l1d_stores"`
	OnL1iLoadMisses      *ebpf.ProgramSpec `ebpf:"on_l1i_load_misses"`
	OnL1iLoads           *ebpf.ProgramSpec `ebpf:"on_l1i_loads"`
	OnL1iPrefetches      *ebpf.ProgramSpec `ebpf:"on_l1i_prefetches"`
	OnLlcLoadMisses      *ebpf.ProgramSpec `ebpf:"on_llc_load_misses"`
	OnLlcLoads           *ebpf.ProgramSpec `ebpf:"on_llc_loads"`
	OnLlcPrefetchMisses  *ebpf.ProgramSpec `ebpf:"on_llc_prefetch_misses"`
	OnLlcPrefetches      *ebpf.ProgramSpec `ebpf:"on_llc_prefetches"`
	OnLlcStoreMisses     *ebpf.ProgramSpec `ebpf:"on_llc_store_misses"`
	OnLlcStores          *ebpf.ProgramSpec `ebpf:"on_llc_stores"`
	OnRefCycles          *ebpf.ProgramSpec `ebpf:"on_ref_cycles"`
	OnTlbLoadMisses      *ebpf.ProgramSpec `ebpf:"on_tlb_load_misses"`
	OnTlbLoads           *ebpf.ProgramSpec `ebpf:"on_tlb_loads"`
}

// hardwareMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hardwareMapSpecs struct {
	Stats *ebpf.MapSpec `ebpf:"stats"`
}

// hardwareVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hardwareVariableSpecs struct {
}

// hardwareObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHardwareObjects or ebpf.CollectionSpec.LoadAndAssign.
type hardwareObjects struct {
	hardwarePrograms
	hardwareMaps
	hardwareVariables
}

func (o *hardwareObjects) Close() error {
	return _HardwareClose(
		&o.hardwarePrograms,
		&o.hardwareMaps,
	)
}

// hardwareMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHardwareObjects or ebpf.CollectionSpec.LoadAndAssign.
type hardwareMaps struct {
	Stats *ebpf.Map `ebpf:"stats"`
}

func (m *hardwareMaps) Close() error {
	return _HardwareClose(
		m.Stats,
	)
}

// hardwareVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHardwareObjects or ebpf.CollectionSpec.LoadAndAssign.
type hardwareVariables struct {
}

// hardwarePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHardwareObjects or ebpf.CollectionSpec.LoadAndAssign.
type hardwarePrograms struct {
	OnBpuLoadMisses      *ebpf.Program `ebpf:"on_bpu_load_misses"`
	OnBpuLoads           *ebpf.Program `ebpf:"on_bpu_loads"`
	OnBranchMisses       *ebpf.Program `ebpf:"on_branch_misses"`
	OnBranches           *ebpf.Program `ebpf:"on_branches"`
	OnCacheMisses        *ebpf.Program `ebpf:"on_cache_misses"`
	OnCacheReferences    *ebpf.Program `ebpf:"on_cache_references"`
	OnCpuCycles          *ebpf.Program `ebpf:"on_cpu_cycles"`
	OnDtlbLoadMisses     *ebpf.Program `ebpf:"on_dtlb_load_misses"`
	OnDtlbLoads          *ebpf.Program `ebpf:"on_dtlb_loads"`
	OnDtlbPrefetchMisses *ebpf.Program `ebpf:"on_dtlb_prefetch_misses"`
	OnDtlbPrefetches     *ebpf.Program `ebpf:"on_dtlb_prefetches"`
	OnDtlbStoreMisses    *ebpf.Program `ebpf:"on_dtlb_store_misses"`
	OnDtlbStores         *ebpf.Program `ebpf:"on_dtlb_stores"`
	OnInstructions       *ebpf.Program `ebpf:"on_instructions"`
	OnL1dLoadMisses      *ebpf.Program `ebpf:"on_l1d_load_misses"`
	OnL1dLoads           *ebpf.Program `ebpf:"on_l1d_loads"`
	OnL1dPrefetchMisses  *ebpf.Program `ebpf:"on_l1d_prefetch_misses"`
	OnL1dPrefetches      *ebpf.Program `ebpf:"on_l1d_prefetches"`
	OnL1dStoreMisses     *ebpf.Program `ebpf:"on_l1d_store_misses"`
	OnL1dStores          *ebpf.Program `ebpf:"on_l1d_stores"`
	OnL1iLoadMisses      *ebpf.Program `ebpf:"on_l1i_load_misses"`
	OnL1iLoads           *ebpf.Program `ebpf:"on_l1i_loads"`
	OnL1iPrefetches      *ebpf.Program `ebpf:"on_l1i_prefetches"`
	OnLlcLoadMisses      *ebpf.Program `ebpf:"on_llc_load_misses"`
	OnLlcLoads           *ebpf.Program `ebpf:"on_llc_loads"`
	OnLlcPrefetchMisses  *ebpf.Program `ebpf:"on_llc_prefetch_misses"`
	OnLlcPrefetches      *ebpf.Program `ebpf:"on_llc_prefetches"`
	OnLlcStoreMisses     *ebpf.Program `ebpf:"on_llc_store_misses"`
	OnLlcStores          *ebpf.Program `ebpf:"on_llc_stores"`
	OnRefCycles          *ebpf.Program `ebpf:"on_ref_cycles"`
	OnTlbLoadMisses      *ebpf.Program `ebpf:"on_tlb_load_misses"`
	OnTlbLoads           *ebpf.Program `ebpf:"on_tlb_loads"`
}

func (p *hardwarePrograms) Close() error {
	return _HardwareClose(
		p.OnBpuLoadMisses,
		p.OnBpuLoads,
		p.OnBranchMisses,
		p.OnBranches,
		p.OnCacheMisses,
		p.OnCacheReferences,
		p.OnCpuCycles,
		p.OnDtlbLoadMisses,
		p.OnDtlbLoads,
		p.OnDtlbPrefetchMisses,
		p.OnDtlbPrefetches,
		p.OnDtlbStoreMisses,
		p.OnDtlbStores,
		p.OnInstructions,
		p.OnL1dLoadMisses,
		p.OnL1dLoads,
		p.OnL1dPrefetchMisses,
		p.OnL1dPrefetches,
		p.OnL1dStoreMisses,
		p.OnL1dStores,
		p.OnL1iLoadMisses,
		p.OnL1iLoads,
		p.OnL1iPrefetches,
		p.OnLlcLoadMisses,
		p.OnLlcLoads,
		p.OnLlcPrefetchMisses,
		p.OnLlcPrefetches,
		p.OnLlcStoreMisses,
		p.OnLlcStores,
		p.OnRefCycles,
		p.OnTlbLoadMisses,
		p.OnTlbLoads,
	)
}

func _HardwareClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hardware_bpfeb.o
var _HardwareBytes []byte
