// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package kernel

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type latencyMigrationEventT struct {
	_              structs.HostLayout
	TimestampStart uint64
	TimestampEnd   uint64
	Latency        uint64
	Pid            uint32
	SourceCpu      uint32
	TargetCpu      uint32
	CgroupId       uint32
}

// loadLatency returns the embedded CollectionSpec for latency.
func loadLatency() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LatencyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load latency: %w", err)
	}

	return spec, err
}

// loadLatencyObjects loads latency and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*latencyObjects
//	*latencyPrograms
//	*latencyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLatencyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLatency()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// latencySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latencySpecs struct {
	latencyProgramSpecs
	latencyMapSpecs
	latencyVariableSpecs
}

// latencyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latencyProgramSpecs struct {
	RawTpSchedSwitch           *ebpf.ProgramSpec `ebpf:"raw_tp_sched_switch"`
	TracepointSchedMigrateTask *ebpf.ProgramSpec `ebpf:"tracepoint_sched_migrate_task"`
}

// latencyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latencyMapSpecs struct {
	ContainerMap *ebpf.MapSpec `ebpf:"container_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	MigrationMap *ebpf.MapSpec `ebpf:"migration_map"`
}

// latencyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latencyVariableSpecs struct {
}

// latencyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type latencyObjects struct {
	latencyPrograms
	latencyMaps
	latencyVariables
}

func (o *latencyObjects) Close() error {
	return _LatencyClose(
		&o.latencyPrograms,
		&o.latencyMaps,
	)
}

// latencyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type latencyMaps struct {
	ContainerMap *ebpf.Map `ebpf:"container_map"`
	Events       *ebpf.Map `ebpf:"events"`
	MigrationMap *ebpf.Map `ebpf:"migration_map"`
}

func (m *latencyMaps) Close() error {
	return _LatencyClose(
		m.ContainerMap,
		m.Events,
		m.MigrationMap,
	)
}

// latencyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type latencyVariables struct {
}

// latencyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type latencyPrograms struct {
	RawTpSchedSwitch           *ebpf.Program `ebpf:"raw_tp_sched_switch"`
	TracepointSchedMigrateTask *ebpf.Program `ebpf:"tracepoint_sched_migrate_task"`
}

func (p *latencyPrograms) Close() error {
	return _LatencyClose(
		p.RawTpSchedSwitch,
		p.TracepointSchedMigrateTask,
	)
}

func _LatencyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed latency_bpfel.o
var _LatencyBytes []byte
