// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package kernel

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type llcLlcEventT struct {
	_                  structs.HostLayout
	Pid                uint32
	Cpu                uint32
	CgroupId           uint32
	_                  [4]byte
	ReadReferences     uint64
	ReadMisses         uint64
	ReadHits           uint64
	WriteReferences    uint64
	WriteMisses        uint64
	WriteHits          uint64
	PrefetchReferences uint64
	PrefetchMisses     uint64
	PrefetchHits       uint64
	TotalReferences    uint64
	TotalMisses        uint64
	TotalHits          uint64
}

// loadLlc returns the embedded CollectionSpec for llc.
func loadLlc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LlcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load llc: %w", err)
	}

	return spec, err
}

// loadLlcObjects loads llc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*llcObjects
//	*llcPrograms
//	*llcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLlcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLlc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// llcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type llcSpecs struct {
	llcProgramSpecs
	llcMapSpecs
	llcVariableSpecs
}

// llcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type llcProgramSpecs struct {
	LlcPrefetchHitHandler  *ebpf.ProgramSpec `ebpf:"llc_prefetch_hit_handler"`
	LlcPrefetchMissHandler *ebpf.ProgramSpec `ebpf:"llc_prefetch_miss_handler"`
	LlcReadHitHandler      *ebpf.ProgramSpec `ebpf:"llc_read_hit_handler"`
	LlcReadMissHandler     *ebpf.ProgramSpec `ebpf:"llc_read_miss_handler"`
	LlcWriteHitHandler     *ebpf.ProgramSpec `ebpf:"llc_write_hit_handler"`
	LlcWriteMissHandler    *ebpf.ProgramSpec `ebpf:"llc_write_miss_handler"`
}

// llcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type llcMapSpecs struct {
	LlcContainerMap *ebpf.MapSpec `ebpf:"llc_container_map"`
	LlcStatsMap     *ebpf.MapSpec `ebpf:"llc_stats_map"`
}

// llcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type llcVariableSpecs struct {
}

// llcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLlcObjects or ebpf.CollectionSpec.LoadAndAssign.
type llcObjects struct {
	llcPrograms
	llcMaps
	llcVariables
}

func (o *llcObjects) Close() error {
	return _LlcClose(
		&o.llcPrograms,
		&o.llcMaps,
	)
}

// llcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLlcObjects or ebpf.CollectionSpec.LoadAndAssign.
type llcMaps struct {
	LlcContainerMap *ebpf.Map `ebpf:"llc_container_map"`
	LlcStatsMap     *ebpf.Map `ebpf:"llc_stats_map"`
}

func (m *llcMaps) Close() error {
	return _LlcClose(
		m.LlcContainerMap,
		m.LlcStatsMap,
	)
}

// llcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLlcObjects or ebpf.CollectionSpec.LoadAndAssign.
type llcVariables struct {
}

// llcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLlcObjects or ebpf.CollectionSpec.LoadAndAssign.
type llcPrograms struct {
	LlcPrefetchHitHandler  *ebpf.Program `ebpf:"llc_prefetch_hit_handler"`
	LlcPrefetchMissHandler *ebpf.Program `ebpf:"llc_prefetch_miss_handler"`
	LlcReadHitHandler      *ebpf.Program `ebpf:"llc_read_hit_handler"`
	LlcReadMissHandler     *ebpf.Program `ebpf:"llc_read_miss_handler"`
	LlcWriteHitHandler     *ebpf.Program `ebpf:"llc_write_hit_handler"`
	LlcWriteMissHandler    *ebpf.Program `ebpf:"llc_write_miss_handler"`
}

func (p *llcPrograms) Close() error {
	return _LlcClose(
		p.LlcPrefetchHitHandler,
		p.LlcPrefetchMissHandler,
		p.LlcReadHitHandler,
		p.LlcReadMissHandler,
		p.LlcWriteHitHandler,
		p.LlcWriteMissHandler,
	)
}

func _LlcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed llc_bpfeb.o
var _LlcBytes []byte
