// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package kernel

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type procProcEventT struct {
	_              structs.HostLayout
	Pid            uint32
	CgroupId       uint32
	StartTimestamp uint64
	EndTimestamp   uint64
	Latency        uint64
}

// loadProc returns the embedded CollectionSpec for proc.
func loadProc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load proc: %w", err)
	}

	return spec, err
}

// loadProcObjects loads proc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*procObjects
//	*procPrograms
//	*procMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// procSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procSpecs struct {
	procProgramSpecs
	procMapSpecs
	procVariableSpecs
}

// procProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procProgramSpecs struct {
	KprobeDoExit *ebpf.ProgramSpec `ebpf:"kprobe_do_exit"`
	TraceExecve  *ebpf.ProgramSpec `ebpf:"trace_execve"`
}

// procMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procMapSpecs struct {
	Events              *ebpf.MapSpec `ebpf:"events"`
	ProcessContainerMap *ebpf.MapSpec `ebpf:"process_container_map"`
	ProcessMonitorMap   *ebpf.MapSpec `ebpf:"process_monitor_map"`
}

// procVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procVariableSpecs struct {
}

// procObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type procObjects struct {
	procPrograms
	procMaps
	procVariables
}

func (o *procObjects) Close() error {
	return _ProcClose(
		&o.procPrograms,
		&o.procMaps,
	)
}

// procMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type procMaps struct {
	Events              *ebpf.Map `ebpf:"events"`
	ProcessContainerMap *ebpf.Map `ebpf:"process_container_map"`
	ProcessMonitorMap   *ebpf.Map `ebpf:"process_monitor_map"`
}

func (m *procMaps) Close() error {
	return _ProcClose(
		m.Events,
		m.ProcessContainerMap,
		m.ProcessMonitorMap,
	)
}

// procVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type procVariables struct {
}

// procPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcObjects or ebpf.CollectionSpec.LoadAndAssign.
type procPrograms struct {
	KprobeDoExit *ebpf.Program `ebpf:"kprobe_do_exit"`
	TraceExecve  *ebpf.Program `ebpf:"trace_execve"`
}

func (p *procPrograms) Close() error {
	return _ProcClose(
		p.KprobeDoExit,
		p.TraceExecve,
	)
}

func _ProcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed proc_bpfel.o
var _ProcBytes []byte
